# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [2]:
import numpy as np

list_of_lists = [[5, 6, 7,], [3, 5, 2], [-2, -9, 7]]

list_basic_matrix = np.array(list_of_lists)

print(list_basic_matrix)

[[ 5  6  7]
 [ 3  5  2]
 [-2 -9  7]]


2. Make a 3D numpy matrix from a Python list of lists of lists!

In [7]:
threeD_matrix = list_basic_matrix[np.newaxis,:]

print(threeD_matrix)

[[[ 5  6  7]
  [ 3  5  2]
  [-2 -9  7]]]


3. Create a 5x3 array of Gaussian random numbers. 

In [9]:
random_numbers = np.random.randn(5,3)

print(random_numbers)

[[-0.06622275 -1.11699975  0.03360409]
 [ 0.27645997  0.59766081 -0.16034654]
 [-0.25424404  1.31683292  1.40471982]
 [ 0.12954561  1.37178549  1.09023872]
 [-1.19209035 -1.07422884 -1.41410314]]


4. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [113]:
row = 0 # start at first row
column = 0 # start at first column

for i in random_numbers[row:]:
    for row in random_numbers: # this is about the columns
        while row <= 4: # do this for all 5 columns
            row+=1 # increase column until we've done all 5
            break
    for column in random_numbers[:column]: # this is about the rows
        while column <=2: # do this for all 3 columns
            column+=1 # increase row until we've done all 3
            print("the value", random_numbers[row, column], "is located at", [row, column]) # announce the value and its indexes

TypeError: 'int' object is not subscriptable

5. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [68]:
random_numbers_more = (random_numbers * 3) + 10

print("the mean is", (np.mean(random_numbers_more)))
print("the standard deviation is", (np.std(random_numbers_more)))

the mean is 10.1885223996828
the standard deviation is 2.8021956657191525


6. Count the number of values in your new array that are below 7.

In [45]:
random_numbers_more <= 11

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True, False, False],
       [ True,  True,  True]])

7. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [53]:
sequence = np.arange(2, 20, 2)

print(sequence)

[ 2  4  6  8 10 12 14 16 18]


8. Get the second and third rows of your array.

In [66]:
print(f'row 2', (random_numbers_more[1,:]), 'row 3', (random_numbers_more[2,:]) )

row 2 [5.76459966 8.97660807 1.39653455] row 3 [ 0.45755959 16.16832916 17.04719815]


9. Compute the mean of the columns of your array.

In [77]:
print("the mean of column 1 is", (np.mean(random_numbers_more[:,0])))
print("the mean of column 2 is", (np.mean(random_numbers_more[:,1])))
print("the mean of column 3 is", (np.mean(random_numbers_more[:,2])))

the mean of column 1 is 9.3360690637893
the mean of column 2 is 10.657030369556292
the mean of column 3 is 10.57246776570281
